export const notFoundQuotes = [
`Whoah, you've gone too far out. You won't find any music here 🚫`,
`I've looked in every record sleeve yet I can't find what you're looking for`,
`1, 2, 3, 4, how many errors are in my store?`,
`"Hello darkness, my old friend" 🌃`,
`We could've spent more time making the website better but here we go writing random stuff. Yeah, no, your page was not found`,
`Looks like this page hit a sour note and needs a quick tune-up`,
`This page is as elusive as a unicorn on roller skates`,
`The page you're looking for got lost in the rhythm of the internet. Let's try to find the beat again!`,
`Oops! It seems we've hit a broken chord here. Time to retune and try another string`,
`This page is experiencing stage fright and decided to hide behind the curtains :(`,
`This page is in a jam session with the 404 band. They're playing an invisible gig tonight`,
`We're searching for this page like it's the last vinyl record in existence 👀`,
`Looks like the page you requested is taking a coffee break in the green room. It'll be back on stage soon!`,
`The music stopped, but the page keeps dancing to its own beat`,
`Whoops! This page took a detour to the wrong concert hall. Let's get it back on track`,
`The page you're seeking is singing a ballad in the binary blues`,
`This page is on a world tour of the web, and it got lost somewhere between the hits and misses`,
`It appears the page's sheet music is missing. We'll have to improvise!`,
`This page is practicing its disappearing act for its next magic trick. Abracadabra, it's gone! 🪄`,
`This page went on a world tour but forgot to leave a trail of breadcrumbs. Can you sing it back?`,
`Whoa! The page you're looking for is dancing to its own rhythm. It'll return to the main stage soon`,
`It seems this page got caught up in a never-ending encore. We'll try to wrap it up`,
`This page joined the choir of missing links. We're harmonizing the search to find it 🎵`,
`Oops! It looks like this page wandered into a digital mosh pit. Let's rescue it from the crowd`,
`This page is moonwalking in cyberspace. Time to bring it back to reality!`,
`This page is practicing its scales, trying to reach that perfect note. Stay tuned for its return`,
`We're searching for this page like it's the last record store in town. It'll be back on the shelves soon!`,
`Sorry, but this page has gone on a rock 'n' roll road trip. We'll bring it back from the wild tour`,
`The page you're seeking is on an intergalactic tour with the interstellar orchestra. It'll be back from space soon!`,
`Whoops! It seems this page is tangled in its headphone wires. We're untangling it for you 🎧`,
`This page is experiencing some stage fright. We're giving it a pep talk to get back in the spotlight 💪🏼`,
`This page is tap-dancing through the internet's backstage corridors. We're directing it back to center stage!`
]
export default { notFoundQuotes };